name: Deploy AWS Infra with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform -chdir=infra init

      # 5️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=infra plan -out=tfplan

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve tfplan
