name: Deploy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true

permissions:
  contents: write
  actions: write

env:
  TF_WORKING_DIR: infra  # Folder containing Terraform files

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      # 5️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan -out=tfplan

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve tfplan
