name: Terraform Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra  # path to your Terraform files

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 3️⃣ Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4️⃣ Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # 5️⃣ Validate Terraform configuration
      - name: Validate Terraform
        run: terraform validate

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        id: apply
        run: |
          set -o pipefail
          terraform apply -auto-approve tfplan 2>&1 | tee terraform.log
          # Check for common AWS errors
          if grep -q "VpcLimitExceeded" terraform.log; then
            echo "❌ VPC limit exceeded. Please delete unused VPCs or increase limit."
            exit 1
          fi
          if grep -q "BucketAlreadyExists" terraform.log; then
            echo "❌ S3 bucket already exists. Choose a unique bucket name."
            exit 1
          fi
