name: Deploy Python App on EC2

on:
  workflow_dispatch:
    inputs:
      PROJECT_ID:
        description: "Project ID"
        required: true
      ORGANIZATION_ID:
        description: "Organization ID"
        required: true
      CLOUD_TYPE:
        description: "Cloud Type"
        required: true
      API_KEY:
        description: "API Key"
        required: true
      BLAZEOPS_BASE_URL:
        description: "Base URL for BlazeOps"
        required: true
      AGENT_ID:
        description: "Agent ID"
        required: true
      branch:
        description: "GitHub branch"
        required: true
      github_token:
        description: "GitHub token"
        required: true
      aws_config:
        description: "AWS Credentials & Region [JSON String]"
        required: true
        type: string
        default: '{}'

permissions:
  contents: write
  actions: write

env:
  AWS_REGION: us-east-2
  IMAGE_NAME: blazeops-agent-backend-api
  ENV: staging
  IMAGE_TAG: latest
  AWS_ACCESS_KEY_ID: ${{ fromJson(github.event.inputs.aws_config).access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ fromJson(github.event.inputs.aws_config).secret_key }}
  AWS_ACCOUNT_ID: ${{ fromJson(github.event.inputs.aws_config).aws_account_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (infra code)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Parse AWS Config
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ fromJson(github.event.inputs.aws_config).access_key }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ fromJson(github.event.inputs.aws_config).secret_key }}" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=${{ fromJson(github.event.inputs.aws_config).aws_account_id }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2

      - name: Authenticate with Terraform Cloud
        run: |
          echo 'credentials "app.terraform.io" {
            token = "${{ secrets.TF_API_TOKEN }}"
          }' > $HOME/.terraformrc
